// Auto-generated by Supabase MCP — do not hand-edit.
// Regenerate after every schema migration:
//   Supabase:generate_typescript_types → project_id: pyeccxjwbjfrigcyyvar

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
